#!/usr/bin/env python3
"""Convert CT DICOM series into windowed JPEG stacks for the viewer.

Usage:
    pip install pydicom numpy pillow
    python3 tools/convert_dicom.py <dicom-root> non-contrast=74756 arterial=63735 \
        portal-venous=31168 delayed=<series-folder>

Each phase=folder pair names a sub-folder of <dicom-root> holding one series.
Slices are sorted superior -> inferior, rendered with an abdominal soft-tissue
window (W400 / L40), written to images/<phase>/NNN.jpg, and js/series.js is
rewritten with slice counts and table positions so phases stay in sync.
"""
import glob
import json
import os
import sys

import numpy as np
import pydicom
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WINDOW_WIDTH, WINDOW_LEVEL = 400, 40


def convert(folder, phase):
    slices = [pydicom.dcmread(f) for f in glob.glob(os.path.join(folder, "*.dcm"))]
    slices = [d for d in slices if getattr(d, "Modality", "") == "CT"]
    slices.sort(key=lambda d: -float(d.ImagePositionPatient[2]))
    out_dir = os.path.join(ROOT, "images", phase)
    os.makedirs(out_dir, exist_ok=True)
    for old in glob.glob(os.path.join(out_dir, "*.jpg")):
        os.remove(old)
    lo = WINDOW_LEVEL - WINDOW_WIDTH / 2
    z = []
    for i, d in enumerate(slices):
        hu = d.pixel_array.astype(np.float32) * float(d.RescaleSlope) + float(d.RescaleIntercept)
        img = np.clip((hu - lo) / WINDOW_WIDTH * 255, 0, 255).astype(np.uint8)
        Image.fromarray(img).save(os.path.join(out_dir, f"{i:03d}.jpg"), quality=82, optimize=True)
        z.append(round(float(d.ImagePositionPatient[2]), 2))
    print(f"{phase}: {len(slices)} slices, z {z[0]} to {z[-1]} mm")
    return {"count": len(slices), "z": z}


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    src = sys.argv[1]
    series_path = os.path.join(ROOT, "js", "series.js")
    series = {}
    if os.path.exists(series_path):
        text = open(series_path).read()
        series = json.loads(text[text.index("{"): text.rindex("}") + 1])
    for pair in sys.argv[2:]:
        phase, folder = pair.split("=", 1)
        series[phase] = convert(os.path.join(src, folder), phase)
    with open(series_path, "w") as f:
        f.write("// Generated by tools/convert_dicom.py: slice count and table position (mm) for each phase,\n")
        f.write("// ordered superior to inferior. Images live in images/<phase>/NNN.jpg.\n")
        f.write("window.SERIES = " + json.dumps(series) + ";\n")


if __name__ == "__main__":
    main()
